# =================global configuration====================
name: euler-encode
seed: 11
split: [0.85, 0.15]     # train val
bar: rich               # 进度条 rich/tqdm
accelerator: gpu        # 训练设备 cpu/gpu
summary: rich           # 模型总结 rich/default
deterministic: false     # 是否可复现
benchmark: true        # 是否加速，和deterministic不可同时为True，deterministic为True时，benchmark参数无效
debug: false             # 是否为debug模式
limit_train_val: [0.1, 0.1]  # 用于debug时的训练部分和测试部分比例
comet_api: agcu7oeqU395peWf6NCNqnTa7
offline: false          # 是否离线训练
save_csv: false
train: true
val: true
self_supervised: false


# =========================dataset=========================
data_dir: ../datasets/speed     # 数据路径
workers: 10            # dataloader workers
ram: false            # 是否使用内存加载数据
imgsz: [480, 768]     # 图片大小 [480, 768]
resize_first: false    # 是否先resize


# =======================encoder-decoder===================
encoder: Linear                     # Linear/Gauss
stride: 5                            # 步长 度
n: 2                                # neighbor/tau
s: 0.1                              # ratio/sigma

# ==========================model==========================
backbone: mobilenet_v3_large                      # EfficientNet
pos_dim: 3                              # 位置维度
pretrained: true
neck: TriFPNAtt                            # FPNPAN/BiFPN/AFPN
pool_size: [4, 2, 1]                # 池化尺寸

# ==========================loss===========================
ALPHA: [1, 5]                       # Score = ALPHA[0] * POS_Error + ALPHA[1] * Euler_Error
BETA: [1, 8, 5]                  # Loss = BETA[0] * POS_LOSS + BETA[1] * Euler_LOSS + BETA[2] * CLS_LOSS
pos_loss: MSE                       # 位置损失函数 MAE/MSE/Huber/Log_Cosh (regression loss)
euler_loss: CrossEntropy              # 姿态值损失函数 CrossEntropy/Focal
ori_loss: Arccos

# ==========================train==========================
optimizer: AdamW       # 优化器 Adam/SGD/AdamW
lr0: 0.001            # 初始学习率
momentum: 0.937       # 动量
weight_decay: 0.00001    # 权重衰减
epoch: 300            # 训练轮数
batch_size: 32        # 批次大小

precision: mix        # 训练精度 half/mix/double/full/int8
accumulate_grad_batches: 1            # 累计梯度批次
lr_scheduler: WarmupCosineAnnealingLR # 学习率调度器 WarmupCosineAnnealingLR/ReduceLROnPlateau/MultiStepLR

# WarmupCosineAnnealingLR 参数
warmup_epochs: 5      # warmup轮数
lr_min: 0.00001        # 最小学习率

# ReduceLROnPlateau 参数
factor: 0.1           # 学习率衰减因子
Plateaupatience: 10   # 忍耐轮数

# MultiStepLR 参数
gamma: 0.1            # 学习率衰减因子
milestones: [30, 60]  # 学习率衰减里程碑

# ==========================Augmentation===================
Augmentation:
  p: 0.1

Rotate:
  p: 0.8             # p为图片旋转的概率，(1-p)为相机旋转的概率
  Rotate_img: true
  Rotate_cam: true
  img_angle: 180
  cam_angle: 10

Resize:
  p: 0.5
  ratio: 0.5

CropAndPad:
  p: 0.5

DropBlockSafe:
  p: 0.5
  drop_num: 7